language: node_js

cache: yarn

node_js:
    - '4'
    - '6'
    - stable

install: 'yarn'

script: 'yarn run gamut'

notifications:
    email: false

after_success:
    - bash <(curl -s https://codecov.io/bash)
